function(drishti_check_platforms)
  set(is_ios ${IOS})
  string(COMPARE EQUAL "${CMAKE_SYSTEM_NAME}" "Linux" is_linux)
  string(COMPARE EQUAL "${CMAKE_GENERATOR}" "Xcode" is_xcode)
  message("-- system --")
  message("  MSVC: ${MSVC}")
  message("  APPLE: ${APPLE}")
  message("  ANDROID: ${ANDROID}")
  message("  is_ios: ${is_ios}")
  message("  is_linux: ${is_linux}")
  message("  is_xcode: ${is_xcode}")

  set(is_ios "${is_ios}" PARENT_SCOPE)
  set(is_linux "${is_linux}" PARENT_SCOPE)
  set(is_xcode "${is_xcode}" PARENT_SCOPE)
endfunction()
