function(drishti_check_platforms)
  string(COMPARE EQUAL "${CMAKE_SYSTEM_NAME}" "Linux" is_linux)
  message("-- system --")
  message("  MSVC: ${MSVC}")
  message("  APPLE: ${APPLE}")
  message("  ANDROID: ${ANDROID}")
  message("  IOS: ${IOS}")
  message("  is_linux: ${is_linux}")
  message("  XCODE: ${XCODE}")

  set(is_linux "${is_linux}" PARENT_SCOPE)
endfunction()
