set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
set(CPACK_PACKAGE_DESCRIPTION_FILE "${PROJECT_SOURCE_DIR}/DESCRIPTION")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Drishti SDK")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "drishtisdk")
set(CPACK_PACKAGE_CONTACT "dhirvonen@elucideye.com")
set(CPACK_PACKAGE_MAINTAINER "dhirvonen@elucideye.com")
#set(CPACK_PACKAGE_EXECUTABLES  "test-drishti-segment")
set(CPACK_NSIS_MODIFY_PATH ON)
#set(CPACK_CREATE_DESKTOP_LINKS test-drishti-segment)

set(CPACK_STRIP_FILES TRUE)

include(CPack)